project:
  title: Project Title
  subtitle: Project Role
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus
    deserunt facere harum inventore ipsam ipsum, magnam mollitia nostrum nulla odit
    perspiciatis praesentium quibusdam quidem repellendus sapiente sit sunt ullam
    voluptate.
  lists:
    Achievements:
      - Increased profit margin by 5000%
      - Created documentation of lorem
      - Developed the ipsum feature
